In [1]:
import numpy as np
import matplotlib as plt
from hilp import *
from helper import *
from costs import *
from least_squares import *
from ridge_regression import *
from logistic_regression import *
from cross_validation import *
%load_ext autoreload
%autoreload 2

In [2]:
yb, input_data, ids = load_csv_data('data/train.csv')

In [3]:
yb_te, input_data_te, ids_te = load_csv_data('data/test.csv')

In [4]:
diff = yb.sum()

In [5]:
seed = 12
indices = [i for i, x in enumerate(yb) if x == -1]
np.random.shuffle(indices)
index = np.arange(len(yb))
ind = indices[:int(np.abs(diff))]
ind_keep = ~np.isin(index, ind)
tx_bal = input_data[ind_keep]
y = yb[ind_keep]

In [19]:
y = yb
fact_suppr = 0.8

In [21]:
tx = clean_standardize_data(input_data, fact_suppr)
tx_te = clean_standardize_data(input_data_te, fact_suppr)

[(0, 1), (2, 1), (3, 2), (6, 3), (17, 2), (18, 1), (19, 4)]
(19, 250000)
[(0, 1), (2, 1), (3, 1), (6, 2), (17, 1)]
(18, 250000)
[(0, 1), (2, 1)]
(17, 250000)
[(0, 1), (2, 1), (3, 2), (6, 3), (17, 2), (18, 1), (19, 4)]
(19, 568238)
[(0, 1), (2, 1), (3, 1), (6, 2), (17, 1)]
(18, 568238)
[(0, 1), (2, 1)]
(17, 568238)


In [22]:
k_fold = 4
max_iters = 150
lambdas = [0.01, 0.001, 0.0001, 0.1]
gammas = [0.08, 0.02, 0.1]
degrees = [1]

In [23]:
y[np.where(y == -1)] = 0

In [ ]:
cross_validation_reg_logistic_regression(y, tx, k_fold, max_iters, lambdas, gammas, degrees)

[0.33346826 0.22358934 0.48178945 ... 0.209342   0.34465103 0.40734063]
66.8512
[0.23839193 0.28318481 0.22480309 ... 0.46480188 0.68341821 0.3046863 ]
66.3824
[0.24017566 0.4945991  0.14631589 ... 0.84662456 0.61712587 0.33503096]
65.1072
[0.56254492 0.40632658 0.23607735 ... 0.2141548  0.27757198 0.27664898]
67.3456
[0.17164328 0.21442676 0.37435957 ... 0.18794208 0.27825501 0.51632739]
64.7696
[0.16297631 0.24412316 0.20132105 ... 0.47982325 0.66136974 0.3313285 ]
65.7168
[0.30263448 0.43189812 0.25918039 ... 0.62661451 0.45270904 0.35546429]
66.1808
[0.53751405 0.36117822 0.18689111 ... 0.16005355 0.22333726 0.29387227]
66.168
[0.3375093  0.17358632 0.52190694 ... 0.16977974 0.30908839 0.40545871]
66.5344
[0.16206583 0.23085832 0.21627474 ... 0.43222918 0.72126006 0.27913799]
65.88
[0.28566986 0.4394556  0.20361441 ... 0.56746441 0.48065278 0.37438875]
65.848
[0.51360106 0.34278215 0.19974269 ... 0.19334247 0.21234397 0.27288268]
66.1888
[0.22573526 0.2685811  0.39432837 ... 0.2440