In [1]:
import numpy as np
import matplotlib as plt
from hilp import load_csv_data
from helper import *
from costs import *

In [2]:
yb, input_data, ids = load_csv_data('data/test.csv')

In [3]:
input_data.shape

(568238, 30)

In [4]:
input_data

array([[-999.   ,   79.589,   23.916, ..., -999.   , -999.   ,    0.   ],
       [ 106.398,   67.49 ,   87.949, ..., -999.   , -999.   ,   47.575],
       [ 117.794,   56.226,   96.358, ..., -999.   , -999.   ,    0.   ],
       ...,
       [ 108.497,    9.837,   65.149, ..., -999.   , -999.   ,    0.   ],
       [  96.711,   20.006,   66.942, ..., -999.   , -999.   ,   30.863],
       [  92.373,   80.109,   77.619, ..., -999.   , -999.   ,    0.   ]])

In [5]:
initial_w = np.zeros(30)

In [6]:
for c in input_data.T:
    median = np.median(list(filter(lambda x : x!= -999, c)))
    c[c == -999] = median

In [7]:
input_data

array([[ 1.12541e+02,  7.95890e+01,  2.39160e+01, ..., -1.20000e-02,
        -2.70000e-02,  0.00000e+00],
       [ 1.06398e+02,  6.74900e+01,  8.79490e+01, ..., -1.20000e-02,
        -2.70000e-02,  4.75750e+01],
       [ 1.17794e+02,  5.62260e+01,  9.63580e+01, ..., -1.20000e-02,
        -2.70000e-02,  0.00000e+00],
       ...,
       [ 1.08497e+02,  9.83700e+00,  6.51490e+01, ..., -1.20000e-02,
        -2.70000e-02,  0.00000e+00],
       [ 9.67110e+01,  2.00060e+01,  6.69420e+01, ..., -1.20000e-02,
        -2.70000e-02,  3.08630e+01],
       [ 9.23730e+01,  8.01090e+01,  7.76190e+01, ..., -1.20000e-02,
        -2.70000e-02,  0.00000e+00]])

In [8]:
from logistic_regression import *

In [9]:
initial_w = np.zeros(30)
gamma = 0.1
max_iters = 10

In [10]:
logistic_regression(yb, input_data, initial_w, max_iters, gamma)

[1. 1. 1. ... 1. 1. 1.]
Logistic regression iter. 0/9: loss=nan, w0=12.045155659952316, w1=4.925838724442929


C:\Users\basti\ML\The_MadLads\logistic_regression.py:37: RuntimeWarning: divide by zero encountered in log
  loss = -np.sum(np.dot(y.T,np.log(y_pred)+ np.dot((1-y).T, np.log(1-y_pred)))) /(len(y_pred))


[1. 1. 1. ... 1. 1. 1.]
Logistic regression iter. 1/9: loss=nan, w0=12.045155659952316, w1=4.925838724442929
[1. 1. 1. ... 1. 1. 1.]
Logistic regression iter. 2/9: loss=nan, w0=12.045155659952316, w1=4.925838724442929
[1. 1. 1. ... 1. 1. 1.]
Logistic regression iter. 3/9: loss=nan, w0=12.045155659952316, w1=4.925838724442929
[1. 1. 1. ... 1. 1. 1.]
Logistic regression iter. 4/9: loss=nan, w0=12.045155659952316, w1=4.925838724442929
[1. 1. 1. ... 1. 1. 1.]
Logistic regression iter. 5/9: loss=nan, w0=12.045155659952316, w1=4.925838724442929
[1. 1. 1. ... 1. 1. 1.]
Logistic regression iter. 6/9: loss=nan, w0=12.045155659952316, w1=4.925838724442929
[1. 1. 1. ... 1. 1. 1.]
Logistic regression iter. 7/9: loss=nan, w0=12.045155659952316, w1=4.925838724442929
[1. 1. 1. ... 1. 1. 1.]
Logistic regression iter. 8/9: loss=nan, w0=12.045155659952316, w1=4.925838724442929
[1. 1. 1. ... 1. 1. 1.]
Logistic regression iter. 9/9: loss=nan, w0=12.045155659952316, w1=4.925838724442929


([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
 [array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([ 1.20451557e+01,  4.92583872e+00,  8.11223377e+00,  5.78290937e+00,
          2.18809638e-01,  2.68855809e+01, -4.15146982e-02,  2.37421083e-01,
          1.89926203e+00,  1.58668286e+01,  1.43928858e-01, -1.26825167e-02,
          4.56746303e-02,  3.86940752e+00, -1.19663944e-03, -1.53522257e-03,
          4.67065833e+00, -1.88911706e-03,  5.20638271e-03,  4.16269376e+00,
         -7.98097804e-04,  2.09957809e+01,  9.80251233e-02,  7.72944149e+00,
          1.87115258e-05, -3.22294215e-03,  5.08991835e+00, -9.78708569e-04,
         -2.33218123e-03,  7.32676287e+00]),
  array([ 1.20451557e+01,  4.92583872e+00,  8.11223377e+00,  5.78290937e+00,
          2.18809638e-01,  2.68855809e+01, -4.15146982e-02,  2.37421083e-01,
          1.89926203e+00,  1.58668286e+01,  1.43928858e-01, -1.268251

In [11]:
from least_squares import *

In [12]:
print(least_squares(yb, input_data))

(array([ 1.24743680e-04,  3.34387270e-04, -8.41128816e-04,  2.53695653e-04,
        6.76917736e-02, -1.60837444e-04,  1.51632651e-02,  6.38744073e-02,
        5.27362422e-04,  1.96949142e-01,  2.58317569e-02, -1.15056366e-03,
        2.21593373e-02, -1.95590862e-01, -6.43641874e-05,  1.42930779e-04,
       -1.97027157e-01, -1.08894568e-04,  6.10481281e-05,  1.32390218e-04,
       -2.36815871e-05,  1.12562591e-04,  2.67463578e-01,  4.59535968e-03,
        7.74817478e-05, -2.35381426e-04,  7.17286725e-03,  1.27898439e-04,
       -1.14910593e-04, -2.01753561e-01]), 0.0029122684124714567)
