In [86]:
import numpy as np
import matplotlib as plt
from hilp import *
from helper import *
from costs import *
from least_squares import *
from ridge_regression import *
from logistic_regression import *
from cross_validation import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [115]:
yb, input_data, ids = load_csv_data('data/train.csv')

In [88]:
yb_te, input_data_te, ids_te = load_csv_data('data/test.csv')

In [138]:
diff = yb.sum()

-78666.0


In [156]:
indices = [i for i, x in enumerate(yb) if x == -1]
index = np.arange(len(yb))
ind = indices[:int(np.abs(diff))]
ind_keep = ~np.isin(index, ind)
tx_bal = input_data[ind_keep]
y_bal = yb[ind_keep]

In [157]:
tx = clean_standardize_data(tx_bal)
tx_te = clean_standardize_data(input_data_te)

[(0, 2), (2, 2), (3, 7), (4, 2), (5, 1), (6, 8), (7, 1), (8, 5), (9, 3), (10, 1), (12, 2), (13, 1), (15, 4), (17, 8), (18, 5), (19, 6)]
(19, 171334)
[(0, 2), (2, 2), (3, 6), (4, 2), (5, 1), (6, 1), (7, 4), (8, 2), (9, 1), (11, 1), (12, 1), (14, 3), (16, 7), (17, 4), (18, 5)]
(18, 171334)
[(0, 2), (2, 2), (3, 5), (4, 2), (6, 1), (7, 3), (8, 1), (9, 1), (11, 1), (12, 1), (14, 2), (16, 3), (17, 4)]
(17, 171334)
[(0, 2), (2, 2), (3, 2), (5, 1), (6, 2), (8, 1), (10, 1), (11, 1), (13, 1), (15, 2), (16, 3)]
(16, 171334)
[(0, 2), (2, 2), (3, 2), (5, 1), (6, 1), (8, 1), (10, 1), (11, 1), (15, 1)]
(15, 171334)
[(1, 1), (2, 1), (4, 1), (5, 1), (7, 1), (9, 1), (10, 1), (14, 1)]
(14, 171334)
[(3, 1), (4, 1), (6, 1), (8, 1), (9, 1), (13, 1)]
(13, 171334)
[(8, 1), (3, 1), (12, 1), (5, 1)]
(12, 171334)
[(11, 1), (3, 1)]
(11, 171334)
[(0, 2), (2, 3), (3, 7), (4, 2), (5, 2), (6, 8), (7, 1), (8, 5), (9, 3), (10, 1), (12, 3), (13, 1), (15, 4), (17, 8), (18, 5), (19, 7)]
(19, 568238)
[(0, 2), (2, 3), (3, 6

In [148]:
tx_bal.shape

(171334, 11)

In [ ]:
print(yb.sum())
print(tx.shape)

In [90]:
gammas = [0.08]

In [91]:
initial_w = np.random.uniform(-1,1,tx.shape[1])

In [152]:
k_fold = 4
lambdas = np.logspace(-10, -5, 15)
degrees = [1]
seed = 1
k_indices = build_k_indices(yb, k_fold, seed)
max_iters = 3000


In [37]:
print(initial_w.shape)

(14,)


In [153]:
cross_validation_gradient_descent(y_bal, tx_bal, k_fold, max_iters = max_iters, gammas = gammas, degrees=degrees)

71.10638993299558
71.57565428524735
71.4379100226461
71.30250040856349
71.35561366236313


(0.08, 0.9004415397724217, 71.35561366236313, 1)

In [44]:
model_tr = build_poly(tx, 1)
model_te = build_poly(tx_te, 1)

In [46]:
initial_w = np.random.uniform(-1,1,model_tr.shape[1])

In [47]:
l, w = gradient_descent(yb, model_tr, initial_w, 3000, 0.08)

In [54]:
loss = np.argmin(l)
weight = w[loss]

In [55]:
y_pred = predict_y(model_te, weight)
name = 'gradient_try'
create_csv_submission(ids_te, y_pred, name)

In [ ]:
cross_validation_stochastic_gradient_descent(y, tx, k_fold, initial_w=initial_w, max_iters = max_iters, gammas = gammas, batch_size = 2)

In [284]:
k_fold = 4
lambdas = np.logspace(-5, 0, 9)

In [285]:
lambdas

array([1.00000000e-05, 4.21696503e-05, 1.77827941e-04, 7.49894209e-04,
       3.16227766e-03, 1.33352143e-02, 5.62341325e-02, 2.37137371e-01,
       1.00000000e+00])

In [23]:
from build_polynomial import build_poly

In [216]:
best_lambda,best_rmse, acc, deg = cross_validation_ridge_regression(y, tx, k_fold, lambdas, degrees)

77.3712
77.4
77.3376
77.2096
77.3392
77.3984
77.3088
77.1792
77.3344
77.392
77.304
77.168
77.3536
77.3744
77.3184
77.168
77.3408
77.3712
77.3152
77.1792
77.3312
77.3856
77.3264
77.1856
77.3792
77.3792
77.3312
77.2128
77.3792
77.3792
77.3248
77.192
77.344
77.384
77.3024
77.2064
77.2944
77.3456
77.264
77.1456
77.2064
77.2816
77.2128
77.0848
77.1472
77.1312
77.168
76.896
77.128
77.0832
77.1616
76.8144
77.112
77.032
77.1024
76.8032
77.0528
77.056
77.0784
76.7856
78.1984
78.1056
78.4336
77.9968
78.1776
78.0464
78.3712
77.9968
78.1536
78.0272
78.36
77.9664
78.152
78.0256
78.3584
77.9312
78.1456
78.024
78.3456
77.9216
78.1152
78.016
78.3568
77.9088
78.1024
78.0224
78.3456
77.952
78.1344
78.0256
78.3392
77.9056
78.1104
77.9792
78.328
77.8432
78.1184
77.952
78.2976
77.8224
78.0352
77.9168
78.1536
77.84
77.9712
77.8752
78.1056
77.7488
77.8768
77.7952
78.0656
77.7088
77.8416
77.76
78.0608
77.6928
77.8912
77.768
78.0208
77.6896
79.0544
78.9296
78.8752
78.792
79.0112
78.8656
78.8208
78.728
78.9904


In [241]:
model_tr = build_poly(tx, deg)
model_te = build_poly(tx_te, deg)

In [282]:
print(best_lambda)

1e-10


In [221]:
w = ridge_regression(y, model_tr, best_lambda)

In [242]:
y_pred = predict_y(model_te, w)

name = 'ridge_try'
create_csv_submission(ids_te, y_pred, name)

In [107]:
max_iters = 100
gammas = [0.08, 0.05]
degrees = [1,2]

In [162]:
y_bal[np.where(y_bal == -1)] = 0

In [164]:
cross_validation_logistic_regression(y_bal, tx, k_fold, max_iters, gammas, degrees)

KeyboardInterrupt: 

In [163]:
cross_validation_reg_logistic_regression(y_bal, tx, k_fold, max_iters, lambdas, gammas, degrees)

[0.76293804 0.52429255 0.507693   ... 0.40347747 0.42598295 0.49004139]
nbr 1:0.5330702962668971
47.08285667592744


KeyboardInterrupt: 

In [251]:
initial_w = np.random.uniform(0,1,len(tx.T))

In [212]:
initial_w

array([0.66756879, 0.21507458, 0.42512994, 0.25979745, 0.5482612 ,
       0.12120566, 0.40109407, 0.52266424, 0.66399012, 0.68797437,
       0.02574848, 0.31904886, 0.87852455, 0.47491064, 0.57743159,
       0.25722418, 0.15969363, 0.12730288, 0.50304896, 0.26952168,
       0.87000632, 0.5346475 , 0.73165716, 0.73359706, 0.88299016,
       0.56769155, 0.76946812, 0.42270268, 0.84867666, 0.02780035])

In [256]:
l,ws = logistic_regression(y, tx, initial_w, 80, 0.05)

[array([0.31994921, 0.33445323, 0.16126216, 0.39494692, 0.84394565,
       0.22284416, 0.72329766, 0.96556015, 0.17875997, 0.18089605,
       0.89835453, 0.74269883, 0.47244202, 0.69781485, 0.51932319,
       0.11134055, 0.26564844])]
[0.31994921 0.33445323 0.16126216 0.39494692 0.84394565 0.22284416
 0.72329766 0.96556015 0.17875997 0.18089605 0.89835453 0.74269883
 0.47244202 0.69781485 0.51932319 0.11134055 0.26564844]
-34630.47936342942
[0.30141817 0.30795475 0.15052544 0.4094701  0.84841376 0.23763323
 0.73918186 0.96441776 0.19439216 0.19652186 0.88876938 0.7583355
 0.4880543  0.69045979 0.53496356 0.02252541 0.28081964]
-26140.27694252425
[ 0.28363307  0.28392882  0.14218969  0.42258873  0.85252021  0.25098387
  0.75356626  0.96379316  0.20851643  0.21063985  0.88007403  0.77246421
  0.5021608   0.6839421   0.54909615 -0.05485332  0.29454888]
-20167.984378513764
[ 0.26649472  0.26197748  0.13608819  0.43456912  0.85639342  0.26317107
  0.7667371   0.96366676  0.22142012  0.22353

[-0.2393546  -0.23717667  0.20723037  0.72415563  0.97170237  0.55707083
  1.08899512  1.03683018  0.53377402  0.53568752  0.70752513  1.09788562
  0.82709225  0.59738099  0.87473718 -1.38589813  0.61343471]
-231.70377821637445
[-0.25274837 -0.24966608  0.21002047  0.73154625  0.97474089  0.56456345
  1.09723728  1.03915094  0.54174546  0.54365324  0.70345993  1.10586144
  0.83505658  0.59559667  0.88271928 -1.41687526  0.62126016]
-212.9032346797967
[-0.26613782 -0.26214862  0.21281     0.73893261  0.97777777  0.57205166
  1.10547473  1.0414722   0.54971229  0.55161434  0.69939655  1.11383264
  0.84301632  0.59381346  0.89069677 -1.44783917  0.62908105]
-195.77606318614588
[-0.27952336 -0.27462498  0.21559895  0.74631511  0.98081314  0.57953586
  1.11370791  1.04379387  0.55767492  0.55957125  0.69533479  1.12179965
  0.85097187  0.5920312   0.89867007 -1.47879128  0.63689781]
-180.16039696206713
[-0.29290537 -0.28709576  0.2183873   0.75369407  0.98384714  0.58701642
  1.1219372   1.

-15.169319556484789
[-0.773734   -0.7345929   0.31848693  1.01836699  1.09265161  0.85531226
  1.41711792  1.12976669  0.85110029  0.85278435  0.54545921  1.41538649
  1.14413794  0.5262876   1.19248971 -2.62105485  0.92493994]
-14.422423163200978


In [260]:
idx = np.argmax(l)
w = ws[idx]
y_pred = predict_logistic(tx, initial_w)
print(y_pred.sum())
compute_accuracy(y_pred, y)

[0.32129584 0.25757443 0.70795224 ... 0.22966598 0.09979803 0.20661541]
-170624.0


62.046

In [185]:
def predict_logistic(x: np.ndarray, w: np.ndarray) -> np.ndarray:
    y_pred = sigmoid(x @ w)
    print(y_pred)
    y_pred[np.where(y_pred <= 0.5)] = -1
    y_pred[np.where(y_pred > 0.5)] = 1
    return y_pred

In [292]:
l, w = gradient_descent(y, tx, initial_w, 50, 0.1)

In [293]:
idx = np.argmin(l)
weight = w[idx]
y_pred = predict_y(tx, w)

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "C:\Users\basti\anaconda3\envs\ML\lib\site-packages\IPython\core\interactiveshell.py", line 3369, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\basti\AppData\Local\Temp\ipykernel_14864\3297127648.py", line 3, in <cell line: 3>
    y_pred = predict_y(tx, w)
  File "C:\Users\basti\ML\The_MadLads\helper.py", line 233, in predict_y
    y_pred = tx@w
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 51 is different from 17)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\basti\anaconda3\envs\ML\lib\site-packages\IPython\core\interactiveshell.py", line 1982, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "C:\Users\basti\anaconda3\envs\ML\lib\site-packages\IPython\core\ultratb.py", line 1118, in structured_traceback
    return FormattedTB.

In [ ]:
y_pred.sum()