In [33]:
import numpy as np
import matplotlib as plt
from hilp import load_csv_data
from helper import *
from costs import *
from least_squares import *
from ridge_regression import *
from logistic_regression import *

In [2]:
yb, input_data, ids = load_csv_data('data/test.csv')

In [3]:
input_data.shape

(568238, 30)

In [4]:
input_data

array([[-999.   ,   79.589,   23.916, ..., -999.   , -999.   ,    0.   ],
       [ 106.398,   67.49 ,   87.949, ..., -999.   , -999.   ,   47.575],
       [ 117.794,   56.226,   96.358, ..., -999.   , -999.   ,    0.   ],
       ...,
       [ 108.497,    9.837,   65.149, ..., -999.   , -999.   ,    0.   ],
       [  96.711,   20.006,   66.942, ..., -999.   , -999.   ,   30.863],
       [  92.373,   80.109,   77.619, ..., -999.   , -999.   ,    0.   ]])

In [5]:
initial_w = np.zeros(30)

In [6]:
for c in input_data.T:
    median = np.median(list(filter(lambda x : x!= -999, c)))
    c[c == -999] = median

In [7]:
input_data

array([[ 1.12541e+02,  7.95890e+01,  2.39160e+01, ..., -1.20000e-02,
        -2.70000e-02,  0.00000e+00],
       [ 1.06398e+02,  6.74900e+01,  8.79490e+01, ..., -1.20000e-02,
        -2.70000e-02,  4.75750e+01],
       [ 1.17794e+02,  5.62260e+01,  9.63580e+01, ..., -1.20000e-02,
        -2.70000e-02,  0.00000e+00],
       ...,
       [ 1.08497e+02,  9.83700e+00,  6.51490e+01, ..., -1.20000e-02,
        -2.70000e-02,  0.00000e+00],
       [ 9.67110e+01,  2.00060e+01,  6.69420e+01, ..., -1.20000e-02,
        -2.70000e-02,  3.08630e+01],
       [ 9.23730e+01,  8.01090e+01,  7.76190e+01, ..., -1.20000e-02,
        -2.70000e-02,  0.00000e+00]])

In [34]:
initial_w = np.random.randint(0,1,31)
batch_size = 1
max_iters = 20
gamma = 0.01
lambda_ = 0.01

In [18]:
# standardize the data
std_data, mean, std = standardize(input_data)

In [19]:
# build the model (add 1's for the w0)
tx, y = build_model_data(std_data, yb)

In [20]:
gradient_descent(y, tx, initial_w, max_iters, gamma)

GD iter. 0/19: loss=0.5, w0=0.01, w1=0.008683684348444435
GD iter. 1/19: loss=0.34285033596972836, w0=0.018228875480428917, w1=0.015760182114050496
GD iter. 2/19: loss=0.24812126325273814, w0=0.02508588219982349, w1=0.021590701908378643
GD iter. 3/19: loss=0.19026320178827685, w0=0.030877746326161606, w1=0.026452784591352887
GD iter. 4/19: loss=0.15422163238862135, w0=0.035840171591216365, w1=0.03055974935685636
GD iter. 5/19: loss=0.13112420409985606, w0=0.040154345871968485, w1=0.034075618495121474
GD iter. 6/19: loss=0.11574029172999836, w0=0.043959609907734024, w1=0.037126572106704274
GD iter. 7/19: loss=0.10498458326105095, w0=0.0473631805133971, w1=0.03980973960474708
GD iter. 8/19: loss=0.09703563450186033, w0=0.05044761316116953, w1=0.042199947239914166
GD iter. 9/19: loss=0.09081665946923123, w0=0.05327652955960426, w1=0.04435489690060587
GD iter. 10/19: loss=0.08568968960554202, w0=0.05589901364160139, w1=0.04631914093734386
GD iter. 11/19: loss=0.08127541449300035, w0=0.0583

([0.5,
  0.34285033596972836,
  0.24812126325273814,
  0.19026320178827685,
  0.15422163238862135,
  0.13112420409985606,
  0.11574029172999836,
  0.10498458326105095,
  0.09703563450186033,
  0.09081665946923123,
  0.08568968960554202,
  0.08127541449300035,
  0.07734705341935001,
  0.07376783390540465,
  0.07045415653721532,
  0.0673538902466867,
  0.06443358028659163,
  0.061670906426533924,
  0.0590502340386143,
  0.056559987318936494],
 [array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0]),
  array([ 0.01      ,  0.00868368,  0.0006656 ,  0.00425426,  0.00163087,
         -0.00463566,  0.02539762, -0.00492885, -0.0046147 , -0.00274306,
          0.01298782, -0.00471999, -0.00489638, -0.00483065, -0.0005242 ,
         -0.00488344, -0.00488382,  0.00037821, -0.00488422, -0.00487623,
         -0.00019389, -0.00488299,  0.01876427, -0.00477169,  0.00382314,
         -0.00488207, -0.00488572,  0.00085039, -0.00488319, -0.00488472

In [22]:
stochastic_gradient_descent(y, tx, initial_w, batch_size, max_iters, gamma)

SGD iter. 0/19: loss=0.5, w0=0.01, w1=0.0010883488134605672
SGD iter. 1/19: loss=0.388446158371191, w0=0.018931223635938597, w1=0.00623525405009932
SGD iter. 2/19: loss=0.24344120008292275, w0=0.02721089393022375, w1=0.012933209990210345
SGD iter. 3/19: loss=0.18725552139393634, w0=0.03472170966801592, w1=0.01671595350555126
SGD iter. 4/19: loss=0.14889833708447806, w0=0.04125490757174804, w1=0.021807119882930104
SGD iter. 5/19: loss=0.12171468142637248, w0=0.046875630029632874, w1=0.028642233308724327
SGD iter. 6/19: loss=0.1037848248192258, w0=0.05204888773435543, w1=0.03267363050132336
SGD iter. 7/19: loss=0.0935059027022792, w0=0.05199488674466959, w1=0.032610840192278806
SGD iter. 8/19: loss=0.09359001766408503, w0=0.05652145955537976, w1=0.036138291164716056
SGD iter. 9/19: loss=0.08861140299566547, w0=0.06017725099667276, w1=0.038987162841783725
SGD iter. 10/19: loss=0.08748749190408892, w0=0.06002079071693317, w1=0.03880751693212137
SGD iter. 11/19: loss=0.08723390528978749, w0

([0.5,
  0.388446158371191,
  0.24344120008292275,
  0.18725552139393634,
  0.14889833708447806,
  0.12171468142637248,
  0.1037848248192258,
  0.0935059027022792,
  0.09359001766408503,
  0.08861140299566547,
  0.08748749190408892,
  0.08723390528978749,
  0.08845919947307077,
  0.08983183983090523,
  0.09322049520505309,
  0.09653893407033058,
  0.10240734248776112,
  0.10748415846074606,
  0.11288077207266303,
  0.07235766472914879],
 [array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0]),
  array([ 0.01      ,  0.00108835,  0.00199272,  0.00046069, -0.001245  ,
         -0.00464569,  0.02060986, -0.00490957, -0.00471766, -0.00464186,
          0.00582398, -0.00476553, -0.00495856, -0.00483074, -0.00150708,
         -0.00482364, -0.00473444, -0.00138725, -0.00497568, -0.0046716 ,
         -0.00095849, -0.00511117,  0.00607851, -0.00476947, -0.001046  ,
         -0.00478129, -0.00500057,  0.00052804, -0.00488344, -0.00488513,
  

In [31]:
least_squares(y, tx)

(array([ 9.98435974e-01, -2.79974918e-06,  5.37611243e-07, -1.27949158e-06,
        -4.57276874e-06, -2.85198337e-03,  7.87787997e-07, -1.33100185e-03,
         2.60723220e-04,  1.24631697e-07,  8.01086426e-05,  4.71579815e-05,
         1.58334633e-05,  7.17843912e-04, -9.53674316e-05, -2.57084139e-07,
         2.46739273e-06, -8.39233398e-05,  1.64618541e-10, -5.27506927e-11,
         1.98951966e-12, -1.31876732e-11,  4.97379915e-14, -2.75031198e-09,
        -5.11022336e-11, -1.92244443e-10, -1.01863407e-10, -7.62554464e-11,
        -1.34969014e-09,  1.22781785e-10, -8.20159912e-05]),
 1.9816986649568825e-10)

In [32]:
ridge_regression(y, tx, lambda_)

array([ 1.93785501e-01,  1.19853708e-02,  2.20471543e-05, -7.70834786e-03,
       -8.21151111e-03, -9.12246743e-02,  1.14852885e-03, -9.19499432e-02,
       -8.97526191e-02, -2.33985162e-02,  4.64164937e-02, -9.17762539e-02,
       -9.47047232e-02, -9.37821525e-02, -5.15263586e-02, -9.30399231e-02,
       -9.33596874e-02, -3.88874080e-02, -9.29562299e-02, -9.32584113e-02,
       -4.01187987e-03, -9.29761271e-02,  1.25237773e-02, -9.29443796e-02,
        1.94551957e-03, -9.32788228e-02, -9.44503495e-02, -3.38115911e-03,
       -9.39210854e-02, -9.43539384e-02, -5.23854932e-02])

In [35]:
logistic_regression(y, tx, initial_w, max_iters, gamma)

Logistic regression iter. 0/19: loss=0.6095508480082479, w0=0.01, w1=0.008683684348444435
Logistic regression iter. 1/19: loss=0.5432798167161887, w0=0.019119667676813133, w1=0.016568756473440284
Logistic regression iter. 2/19: loss=0.4898345064530418, w0=0.027479939565090556, w1=0.023765734003225063
Logistic regression iter. 3/19: loss=0.4458888188011732, w0=0.03518972005821683, w1=0.030374592134278185
Logistic regression iter. 4/19: loss=0.40911551655023787, w0=0.04233964626234195, w1=0.03647871961535797
Logistic regression iter. 5/19: loss=0.37788054561660445, w0=0.049003742219134235, w1=0.0421462646222442
Logistic regression iter. 6/19: loss=0.35101233379136054, w0=0.05524259482144874, w1=0.04743297586560574
Logistic regression iter. 7/19: loss=0.327650568016991, w0=0.06110622591363274, w1=0.052384818299288725
Logistic regression iter. 8/19: loss=0.3071490868209136, w0=0.066636358246811, w1=0.057040056653607535
Logistic regression iter. 9/19: loss=0.28901270484426, w0=0.07186814248

([0.6095508480082479,
  0.5432798167161887,
  0.4898345064530418,
  0.4458888188011732,
  0.40911551655023787,
  0.37788054561660445,
  0.35101233379136054,
  0.327650568016991,
  0.3071490868209136,
  0.28901270484426,
  0.27285517319558455,
  0.2583705170967268,
  0.2453130348255886,
  0.23348303984888585,
  0.2227164993708705,
  0.21287737305695947,
  0.2038518595538764,
  0.1955440148701578,
  0.18787237309004196,
  0.18076731010477753],
 [array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0]),
  array([ 0.01      ,  0.00868368,  0.0006656 ,  0.00425426,  0.00163087,
         -0.00463566,  0.02539762, -0.00492885, -0.0046147 , -0.00274306,
          0.01298782, -0.00471999, -0.00489638, -0.00483065, -0.0005242 ,
         -0.00488344, -0.00488382,  0.00037821, -0.00488422, -0.00487623,
         -0.00019389, -0.00488299,  0.01876427, -0.00477169,  0.00382314,
         -0.00488207, -0.00488572,  0.00085039, -0.00488319, -0.0048847

In [36]:
reg_logistic_regression(y, tx, lambda_, initial_w, max_iters, gamma)

Reg Logistic regression iter. 0/19: loss=0.6095508480238322, w0=0.01, w1=0.008683684348444435
Reg Logistic regression iter. 1/19: loss=0.5432798167841847, w0=0.019119667675053305, w1=0.01656875647191211
Reg Logistic regression iter. 2/19: loss=0.4898345065966591, w0=0.027479939560113124, w1=0.023765733998914174
Reg Logistic regression iter. 3/19: loss=0.44588881903528166, w0=0.03518972004879419, w1=0.030374592126137568
Reg Logistic regression iter. 4/19: loss=0.40911551688451137, w0=0.04233964624742148, w1=0.03647871960249711
Reg Logistic regression iter. 5/19: loss=0.37788054605734767, w0=0.049003742197799, w1=0.04214626460389279
Reg Logistic regression iter. 6/19: loss=0.35101233434261353, w0=0.055242594792889295, w1=0.04743297584108781
Reg Logistic regression iter. 7/19: loss=0.3276505686812278, w0=0.061106225877126365, w1=0.052384818268003695
Reg Logistic regression iter. 8/19: loss=0.307149087599503, w0=0.06663635820170606, w1=0.05704005661501606
Reg Logistic regression iter. 9/19

([0.6095508480238322,
  0.5432798167841847,
  0.4898345065966591,
  0.44588881903528166,
  0.40911551688451137,
  0.37788054605734767,
  0.35101233434261353,
  0.3276505686812278,
  0.307149087599503,
  0.2890127057377779,
  0.27285517420403255,
  0.25837051821968804,
  0.24531303606234048,
  0.23348304119848245,
  0.22271650083220482,
  0.21287737462880948,
  0.20385186123493954,
  0.195544016659078,
  0.18787237498542947,
  0.18076731210522484],
 [array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0]),
  array([ 0.01      ,  0.00868368,  0.0006656 ,  0.00425426,  0.00163087,
         -0.00463566,  0.02539762, -0.00492885, -0.0046147 , -0.00274306,
          0.01298782, -0.00471999, -0.00489638, -0.00483065, -0.0005242 ,
         -0.00488344, -0.00488382,  0.00037821, -0.00488422, -0.00487623,
         -0.00019389, -0.00488299,  0.01876427, -0.00477169,  0.00382314,
         -0.00488207, -0.00488572,  0.00085039, -0.00488319, -0.0